// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TunaPianoApiSA.Migrations
{
    [DbContext(typeof(TunaPianoDbContext))]
    [Migration("20230904192801_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TunaPianoApiSA.Models.Artists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 42,
                            Bio = "Beyoncé Giselle Knowles-Carter is an American singer, songwriter, and businesswoman. Known as 'Queen Bey', her artistry, vocal abilities, performances and visual presentations have led her to become a pop culture figure of the 21st century.",
                            Name = "Beyoncé"
                        },
                        new
                        {
                            Id = 2,
                            Age = 42,
                            Bio = "Kelendria Trene Rowland is an American singer, actress, and television personality. She rose to fame in the late 1990s as a member of Destiny's Child, one of the world's best-selling girl groups of all time.",
                            Name = "Kelly Rowland"
                        },
                        new
                        {
                            Id = 3,
                            Age = 44,
                            Bio = "Tenitra Michelle Williams is an American singer and actress. She rose to fame in the early 2000s as a member of Destiny's Child, one of the world's best-selling girl groups of all time.",
                            Name = "Michelle Williams"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Bio = "Aaliyah Dana Haughton was an American singer and actress. She has been credited for helping to redefine contemporary R&B, pop and hip hop, earning her the nicknames the 'Princess of R&B' and 'Queen of Urban Pop'.",
                            Name = "Aaliyah"
                        });
                });

            modelBuilder.Entity("TunaPianoApiSA.Models.Genres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "R&B"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gospel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dance"
                        },
                        new
                        {
                            Id = 5,
                            Description = "House"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hip Hop"
                        });
                });

            modelBuilder.Entity("TunaPianoApiSA.Models.SongGenres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("SongId");

                    b.ToTable("SongGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 4,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 5,
                            SongId = 1
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            SongId = 2
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 2,
                            SongId = 2
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 2,
                            SongId = 3
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 3,
                            SongId = 3
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 1,
                            SongId = 4
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 2,
                            SongId = 4
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 6,
                            SongId = 4
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 1,
                            SongId = 5
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 2,
                            SongId = 5
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 6,
                            SongId = 5
                        });
                });

            modelBuilder.Entity("TunaPianoApiSA.Models.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "RENAISSANCE",
                            ArtistId = 1,
                            Length = 260,
                            Title = "HEATED"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Talk A Good Game",
                            ArtistId = 2,
                            Length = 259,
                            Title = "Red Wine"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Journey To Freedom",
                            ArtistId = 3,
                            Length = 274,
                            Title = "If We Had Your Eyes (ft. Fantasia)"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Aaliyah",
                            ArtistId = 4,
                            Length = 229,
                            Title = "More Than A Woman"
                        },
                        new
                        {
                            Id = 5,
                            Album = "I Care 4 U",
                            ArtistId = 4,
                            Length = 273,
                            Title = "I Care 4 U"
                        });
                });

            modelBuilder.Entity("TunaPianoApiSA.Models.SongGenres", b =>
                {
                    b.HasOne("TunaPianoApiSA.Models.Genres", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPianoApiSA.Models.Songs", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("TunaPianoApiSA.Models.Songs", b =>
                {
                    b.HasOne("TunaPianoApiSA.Models.Artists", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });
#pragma warning restore 612, 618
        }
    }
}
